/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/

export interface Transaction {
  CustomerID: string;
  Date: string;
  Amount: number;
}

export interface RFMRecord {
  customerId: string;
  recency: number; // Days since last purchase
  frequency: number; // Total count of purchases
  monetary: number; // Total spent
  clusterIndex: number;
}

export interface ClusterCentroid {
  recency: number;
  frequency: number;
  monetary: number;
  count: number;
}

export interface ClusterAnalysis {
  id: number;
  name: string; // Generated by Gemini
  description: string; // Generated by Gemini
  strategy: string; // Generated by Gemini
  stats: ClusterCentroid;
}

export interface Artifact {
  id: string;
  html: string;
  status: 'idle' | 'streaming' | 'complete' | 'error';
  styleName: string;
}

export type ProcessingStatus = 'idle' | 'parsing' | 'clustering' | 'analyzing' | 'complete' | 'error';